CREATE TABLE Abone (
    Musteri_ID INT IDENTITY PRIMARY KEY,
    Ad NVARCHAR(50) NOT NULL,
    Soyad NVARCHAR(50) NOT NULL,
	Sifre NVARCHAR(16) NOT NULL,
    Tel_No NVARCHAR(15) UNIQUE NOT NULL,
    Mail NVARCHAR(100) UNIQUE NOT NULL,
    Kayit_Tarihi DATE DEFAULT GETDATE(),
    Adres NVARCHAR(255) NULL
);